import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium,firefox} from 'playwright';import {root} from '../scripts/common.mjs';
const base=process.env.DEMO_URL||'http://127.0.0.1:4181/image-layout-stability-demo/',engine=process.env.BROWSER||'chromium',out=process.env.TEST_OUTPUT||path.join(root,'test-results',engine);fs.mkdirSync(out,{recursive:true});const report={at:new Date().toISOString(),base,engine,scenarios:[],checks:[],axe:[],passed:false};let browser;
try{browser=await(engine==='firefox'?firefox:chromium).launch(engine==='firefox'?{headless:true}:{headless:true,...(process.env.BROWSER_CHANNEL==='bundled'?{}:{channel:process.env.BROWSER_CHANNEL||'chrome'})});report.browser=browser.version();
for(const lang of ['fr','en'])for(const width of [390,1440]){
 const c=await browser.newContext({viewport:{width,height:1000}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+(lang==='en'?'index-en.html':''),{waitUntil:'networkidle'});
 const done=lang==='en'?'Complete.':'Terminé.';const button=p.locator('#launch');await button.click();await p.waitForFunction(text=>document.querySelector('#state').textContent===text,done,{timeout:16000});let values=await p.locator('.movement').allTextContents();assert(!values[0].startsWith('0 '),JSON.stringify(values));assert.equal(values[1],'0 px CSS');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const rects=await p.locator('iframe').evaluateAll(es=>es.map(e=>({width:e.clientWidth,height:e.clientHeight})));assert.deepEqual(rects[0],rects[1]);
 await p.locator('#observe').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,lang+'-'+width+'-complete.png')});await button.click();await button.click();await button.click();await p.waitForFunction(text=>document.querySelector('#state').textContent===text,done,{timeout:16000});assert.deepEqual(await p.locator('.movement').allTextContents(),values);assert.equal(await p.locator('iframe').count(),2);assert.deepEqual(errors,[]);report.scenarios.push({lang,width,replays:4,values,iframeDimensions:rects,passed:true});await c.close();
}
for(const lang of ['fr','en']){const c=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}}),p=await c.newPage();await p.goto(base+(lang==='en'?'index-en.html':''));assert.equal(await p.locator('#interactive').isVisible(),false);assert.equal(await p.locator('tbody tr').count(),12);assert.equal(await p.locator('.static-explanation').isVisible(),true);await p.getByRole('link',{name:lang==='en'?'Unchanged full HTML source A':'Source HTML A complète, inchangée',exact:true}).click();assert((await p.content()).includes('width="1200"')===false);await c.close();report.checks.push({name:'no-js-'+lang,passed:true});}
const c=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await c.newPage();await p.goto(base);assert((await p.locator('#motion-note').textContent()).length>0);await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.className),'skip');await p.keyboard.press('Enter');let reached=false;for(let i=0;i<15;i++){await p.keyboard.press('Tab');if(await p.evaluate(()=>document.activeElement.id==='launch')){assert(await p.evaluate(()=>document.activeElement.matches(':focus-visible')&&getComputedStyle(document.activeElement).outlineStyle!=='none'));reached=true;break;}}assert(reached);await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('#state').textContent==='Terminé.',null,{timeout:16000});report.checks.push({name:'keyboard-reduced-motion',passed:true});
for(const lang of ['fr','en']){await p.goto(base+(lang==='en'?'index-en.html':''));await p.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});for(const f of p.frames().filter(f=>f!==p.mainFrame())){await f.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});const a=await f.evaluate(async()=>{const r=await axe.run(document);return{violations:r.violations.map(v=>({id:v.id,impact:v.impact})),incomplete:r.incomplete.map(v=>v.id)}});report.axe.push({lang,frame:f.url(),...a});assert.equal(a.violations.length,0,JSON.stringify(a));}const result=await p.evaluate(async()=>{const r=await axe.run(document,{iframes:false,runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}});return{violations:r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),incomplete:r.incomplete.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))}});report.axe.push({lang,...result});assert.equal(result.violations.length,0,JSON.stringify(result.violations));}await c.close();
const errorContext=await browser.newContext(),ep=await errorContext.newPage();await ep.route('**/assets/edikka-image.jpg',route=>route.abort());await ep.goto(base);await ep.locator('#launch').click();await ep.waitForFunction(()=>document.querySelector('#state').textContent.includes('Image indisponible'),null,{timeout:16000});assert((await ep.locator('.movement').allTextContents()).every(x=>x==='Indisponible'));report.checks.push({name:'image-failure-no-invented-zero',passed:true});await errorContext.close();
const uc=await browser.newContext();await uc.addInitScript(()=>{if(globalThis.PerformanceObserver)Object.defineProperty(PerformanceObserver,'supportedEntryTypes',{get:()=>['paint','resource','navigation']});});const up=await uc.newPage();await up.goto(base);assert.equal(await up.locator('#metric-support').textContent(),'Mesure indisponible dans ce navigateur');await up.goto(base+'experiments/a.html');await up.waitForFunction(()=>window.imageLab?.finished,null,{timeout:10000});const unavailable=await up.evaluate(()=>window.imageLab.finished);assert.equal(unavailable.cls,null);assert.equal(unavailable.metricStatus,'unavailable');report.checks.push({name:'API-unavailable-null',passed:true});await uc.close();report.passed=true;
}catch(e){report.error=e.stack;process.exitCode=1;}finally{await browser?.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));}
