import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {chromium} from 'playwright';import {root,json,revision,hash,sessionCLS} from './common.mjs';import {startServer} from './server.mjs';import {zipFiles} from './zip.mjs';
const p=json('experiments/protocol.json'),image=json('assets/provenance.json').image,rev=revision();
const series=new Date().toISOString().replace(/[:.]/g,'-'),dir=path.join(root,'results');fs.mkdirSync(dir,{recursive:true});
const write=(name,data)=>fs.writeFileSync(path.join(dir,name),JSON.stringify(data,null,2)+'\n',{flag:'wx'});
const sourceArchive=series+'-sources.zip';fs.writeFileSync(path.join(dir,sourceArchive),zipFiles(root,Object.keys(rev.files)),{flag:'wx'});
const external=process.argv.find(a=>a.startsWith('--base='))?.slice(7);let server,base;
if(external)base=external;else{const s=await startServer({mode:'lab',port:4182,delayMs:p.image_delay_ms});server=s.server;base=s.base;}
let browser;const metadata={schema:'edikka-image-layout-series-v1',id:series,startedAt:new Date().toISOString(),protocolWrittenAt:p.written_at,revision:rev,sourceArchive,plannedTrials:12,runs:[],status:'running'};
try{
 const health=await fetch(new URL('/__experiment',base)).then(r=>r.json());if(health.mode!=='lab'||health.delayMs!==p.image_delay_ms||health.imageSha256!==image.sha256)throw Error('Server does not match the frozen protocol');
 const channel=process.env.BROWSER_CHANNEL||'chrome';browser=await chromium.launch({headless:true,...(channel==='bundled'?{}:{channel})});
 let number=0;for(const viewport of p.viewports)for(const [variant,repetition]of [['a',1],['b',1],['b',2],['a',2],['a',3],['b',3]]){
  const id=series+'-'+String(++number).padStart(2,'0')+'-'+viewport.name+'-'+variant;const target=base+'experiments/'+variant+'.html?run='+encodeURIComponent(id);const startedAt=new Date().toISOString();
  const run={schema:'edikka-image-layout-run-v1',id,series,startedAt,variant,repetition,order:number,environment:'local-delayed-image-response',testedURL:target,revision:rev,sourceArchive,tools:{node:process.version,playwright:json('node_modules/playwright/package.json').version,webVitals:'6.2.2',browser:browser.version(),channel,headless:true},system:{platform:os.platform(),release:os.release(),architecture:os.arch()},viewport,image,conditions:{cache:p.cache,imageDelayMs:p.image_delay_ms,windowMs:p.observation_window_ms,server:health},status:'failed',errors:[],screenshots:{before:id+'-before.png',after:id+'-after.png'}};
  let context;
  try{
   context=await browser.newContext({viewport:{width:viewport.width,height:viewport.height},deviceScaleFactor:viewport.dpr,serviceWorkers:'block',reducedMotion:'no-preference'});const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});const requests=[];
   page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>run.errors.push(e.message));page.on('requestfailed',r=>run.errors.push('Request failed: '+r.url()+': '+r.failure()?.errorText));
   let imageResponse;page.on('response',r=>{if(new URL(r.url()).pathname.endsWith('/assets/edikka-image.jpg'))imageResponse=r;});
   const response=await page.goto(target,{waitUntil:'domcontentloaded',timeout:15000});run.httpStatus=response.status();run.actualURL=page.url();run.userAgent=await page.evaluate(()=>navigator.userAgent);
   await page.waitForFunction(()=>window.imageLab?.before!==null&&window.imageLab?.before!==undefined,null,{timeout:5000});await page.screenshot({path:path.join(dir,run.screenshots.before)});
   await page.waitForFunction(()=>!!window.imageLab?.finished,null,{timeout:11000});run.observation=await page.evaluate(()=>window.imageLab.finished);await page.screenshot({path:path.join(dir,run.screenshots.after)});
   run.requests=requests;run.resourceTiming=await page.evaluate(()=>performance.getEntriesByType('resource').filter(e=>e.name.includes('/assets/edikka-image.jpg')).map(e=>e.toJSON()));
   if(imageResponse){const bytes=await imageResponse.body();run.imageResponse={status:imageResponse.status(),sha256:hash(bytes),bytes:bytes.length,headers:await imageResponse.allHeaders()};}
   const o=run.observation,issues=[];if(run.httpStatus!==200)issues.push('Document HTTP status');if(!o.before||o.before.imageComplete||o.before.at>=o.loadedAt)issues.push('No confirmed pre-load baseline');if(o.loadError||o.loadedAt===null||o.loadedAt>p.observation_window_ms)issues.push('Image not successfully loaded within observation window');if(o.after.naturalWidth!==image.width||o.after.naturalHeight!==image.height)issues.push('Image dimensions mismatch');if(run.imageResponse?.sha256!==image.sha256)issues.push('Image bytes mismatch');if(+run.imageResponse?.headers['x-experiment-delay-ms']!==p.image_delay_ms)issues.push('Response delay mismatch');if(o.visibility.some(v=>v.state!=='visible')||o.interruptions.length)issues.push('Visibility or interaction interruption');if(o.after.viewport.width!==viewport.width||o.after.viewport.height!==viewport.height||o.after.viewport.dpr!==viewport.dpr)issues.push('Viewport mismatch');if(o.before.marker.bottom>viewport.height||o.after.marker.bottom>viewport.height)issues.push('Marker outside viewport');if(requests.some(u=>!u.startsWith(base)))issues.push('Unexpected external request');if(o.metricStatus!=='observed')issues.push('Metric unavailable');else if(Math.abs(sessionCLS(o.events)-o.cls)>1e-10)issues.push('CLS window reconstruction mismatch');if(run.errors.length)issues.push('Browser or resource error');run.validityIssues=issues;run.status=issues.length?'invalid':'valid';
  }catch(e){run.errors.push(e.message.replaceAll(root,'[project]'));run.status='failed';}finally{await context?.close();run.endedAt=new Date().toISOString();const file=id+'-run.json';write(file,run);metadata.runs.push(file);console.log(JSON.stringify({id,variant,viewport:viewport.name,status:run.status,cls:run.observation?.cls,displacement:run.observation?.markerDisplacement,issues:run.validityIssues,errors:run.errors}));}
 }
 metadata.status='completed';
}catch(e){metadata.status='failed';metadata.error=e.message.replaceAll(root,'[project]');process.exitCode=1;}finally{await browser?.close();server?.close();metadata.endedAt=new Date().toISOString();write(series+'-series.json',metadata);}
